export default (Users = [
  {
    id: 1,
    email: 'user1@email.com',
    username: 'user1',
    password: 'password',
    userToken: 'token123',
  },
  {
    id: 2,
    email: 'user2@email.com',
    username: 'user2',
    password: 'pass1234',
    userToken: 'token12345',
  },
  {
    id: 3,
    email: 'testuser@email.com',
    username: 'testuser',
    password: 'testpass',
    userToken: 'testtoken',
  },
  {
    id: 4,
    email: 'jobran41@gmail.com',
    username: 'jobran41@gmail.com',
    password: '11111111',
    userToken: 'token',
  },
  {
    id: 5,
    email: 'foulen1@gmail.com',
    username: 'foulen1',
    password: '11111111',
    userToken: 'token',
  },
  {
    id: 6,
    email: 'foulen2@gmail.com',
    username: 'foulen2',
    password: '11111111',
    userToken: 'token',
  },
  {
    id: 6,
    email: 'foulen6@gmail.com',
    username: 'foulen6',
    password: '11111111',
    userToken: 'token',
  },
  {
    id: 7,
    email: 'foulen7@gmail.com',
    username: 'foulen7',
    password: '11111111',
    userToken: 'token',
  },
  {
    id: 8,
    email: 'foulen8@gmail.com',
    username: 'foulen8',
    password: '11111111',
    userToken: 'token',
  },
  {
    id: 10,
    email: 'testKhawla@gmail.com',
    username: 'testKhawla@gmail.com',
    password: '11111111',
    userToken: 'token',
  },
  {
    id: 11,
    email: 'testKhawla22@gmail.com',
    username: 'testKhawla22@gmail.com',
    password: '11111111',
    userToken: 'token',
  },
  {
    id: 12,
    email: 'testKhawla11@gmail.com',
    username: 'testKhawla11@gmail.com',
    password: '11111111',
    userToken: 'token',
  },
  {
    id: 13,
    email: 'kh44@gmail.com',
    username: 'kh44@gmail.com',
    password: '11111111',
    userToken: 'token',
  },
]);
